runtime: php73
#api_version: 1

handlers:
# Serve images as static resources.
- url: /(.*\.(gif|png|jpg))$
  static_files: static\1
  upload: static/.*\.(gif|png|jpg)$
  #application_readable: true

# Serve php scripts.
- url: /(.+\.php)$
  script: \1

# All URLs beginning with /stylesheets are treated as paths to
# static files in the stylesheets/ directory.
- url: /stylesheets
  static_dir: stylesheets